# Generated by Django 2.1 on 2018-08-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Districts'),
        ),
    ]
