# Generated by Django 2.1 on 2018-08-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_camp_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='locality',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='place',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
