# Generated by Django 2.1 on 2018-08-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180821_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='alternative_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
