# Generated by Django 2.1 on 2018-08-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='locality',
        ),
    ]
