# Generated by Django 2.1 on 2018-08-21 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_camp_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Districts'),
        ),
    ]
