# Generated by Django 2.1 on 2018-08-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_camp_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='district',
        ),
        migrations.AddField(
            model_name='camp',
            name='alt_contact_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='contact_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
