# Generated by Django 2.1 on 2018-08-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20180821_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='excess',
        ),
    ]
