# Generated by Django 2.1 on 2018-08-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_item_excess'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_status',
            field=models.IntegerField(choices=[(1, 'AVILABLE'), (0, 'SHORTAGE')], default=1),
        ),
    ]
