# Generated by Django 2.1 on 2018-08-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_item_stock_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('place', models.CharField(blank=True, max_length=250, null=True)),
                ('short_dic', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
