# Generated by Django 2.1 on 2018-08-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developers',
            new_name='Hero',
        ),
    ]
