# Generated by Django 2.1 on 2018-08-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20180821_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
