# Generated by Django 2.1 on 2018-08-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='reserved1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='reserved2',
            field=models.CharField(blank=True, default=True, max_length=1000),
        ),
    ]
