# Generated by Django 2.1 on 2018-08-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20180821_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='reserved2',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='reserved1',
            new_name='mobile_no',
        ),
        migrations.AddField(
            model_name='hero',
            name='facebook',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
